# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb37fdad6085769c19a318a81757cfca1aa044f1fb9a9059b83ef15ff32956c86627e6f146d528a77c900ed3f3b3d03bf2cbc88f716359db3237b5f1b1f23134

test:
  secret_key_base: 3c2bfc3e41f20d3c685fb48fc3757621da5a2abdf1dd35c5e400eb9789ed9d386eee796355b721442e9cfbac479ba7f782b9ca3763f08eda0ece0f63bc58d8eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
